import AppException from '@shared/exceptions/AppException';
import FakeUsersRepository from '@modules/users/repositories/fakes/FakeUsersRepository';
import ShowProfileService from '@modules/users/services/ShowProfileService';

let fakeUsersRepository: FakeUsersRepository;
let showProfile: ShowProfileService;

describe('ShowProfileService', () => {
  beforeEach(() => {
    fakeUsersRepository = new FakeUsersRepository();

    showProfile = new ShowProfileService(fakeUsersRepository);
    showProfile.setTranslateFunction(() => 'Error');
  });

  it('should be able to show the user profile', async () => {
    const user = await fakeUsersRepository.create({
      name: 'John Doe',
      email: 'johndoe@example.com',
      password: '123456',
    });

    const profile = await showProfile.execute({
      user_id: user.id,
    });

    expect(profile.name).toBe(user.name);
    expect(profile.email).toBe(user.email);
  });

  it('should NOT be able to show the user profile it the user does not exists', async () => {
    await expect(
      showProfile.execute({
        user_id: 'fake-id',
      }),
    ).rejects.toBeInstanceOf(AppException);
  });
});
